title: De La Salle
url: https://delasalle.edu.sg
favicon: /images/photo1668084061.jpeg
colors:
  primary-color: "#60a906"
  secondary-color: "#2c4f02"
  media-colors:
    - title: media-color-one
      color: "#2c4f02"
    - title: media-color-two
      color: "#2c4f02"
    - title: media-color-three
      color: "#b8e986"
    - title: media-color-four
      color: "#f5a623"
    - title: media-color-five
      color: "#f8e71c"
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d1ygz0wnkrlyum.amplifyapp.com
prod: https://master.d1ygz0wnkrlyum.amplifyapp.com
shareicon: /images/photo1668084061.jpeg
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
